"""Installable-product and beginner-experience services."""

from artifex.distribution.approvals import ApprovalStore
from artifex.distribution.artifact import (
    ARTIFACT_MANIFEST_NAME,
    VerifiedArtifact,
    create_artifact_manifest,
    verify_artifact,
)
from artifex.distribution.beginner import BeginnerJourneyResult, start_beginner_journey
from artifex.distribution.client_setup import (
    ClientConfigurationError,
    ClientMutation,
    ClientSetupPlan,
    apply_client_enable,
    apply_client_rollback,
    discover_bridge_command,
    plan_client_enable,
    plan_client_rollback,
    verify_client_integration,
)
from artifex.distribution.discovery import SUPPORTED_TOOLS, detect_resources, discover_environment
from artifex.distribution.doctor import run_distribution_doctor, run_installation_doctor
from artifex.distribution.installed_state import (
    INSTALLATION_RECORD_NAME,
    INSTALLATION_RECORD_SCHEMA,
    InstalledStateRecord,
    StateMigrationResult,
    canonical_state_root,
    discover_canonical_state_root,
    installation_record_path,
    migrate_legacy_state,
    read_installed_state_record,
    remove_installed_state_record,
    write_installed_state_record,
)
from artifex.distribution.lifecycle import (
    InstallResult,
    complete_deferred_uninstall,
    install,
    install_plan,
    uninstall,
    uninstall_plan,
    upgrade,
    upgrade_plan,
)
from artifex.distribution.models import (
    DecisionExplanation,
    DistributionDoctorReport,
    DoctorFinding,
    EnvironmentDiscovery,
    ExperienceMode,
    ResourceEnvelope,
    RiskLevel,
    SetupAction,
    SetupPlan,
    ToolDiscovery,
)
from artifex.distribution.presentation import (
    explain_decision,
    presentation_policy,
    require_approval,
)
from artifex.distribution.service_registration import (
    SERVICE_REGISTRATION_MANIFEST_NAME,
    WINDOWS_11_CORE_PLATFORM_ID,
    ServiceRegistrationAdapter,
    ServiceRegistrationDriftError,
    ServiceRegistrationError,
    ServiceRegistrationManager,
    ServiceRegistrationManifest,
    ServiceRegistrationObservation,
    ServiceRegistrationPlan,
    ServiceRegistrationResult,
    ServiceRegistrationRollbackError,
    ServiceRegistrationSpec,
    UnsupportedServicePlatformError,
    UnsupportedServiceRegistrationAdapter,
    WindowsTaskSchedulerRegistrationAdapter,
    read_service_registration_manifest,
    select_service_registration_adapter,
)
from artifex.distribution.setup import apply_integration_setup, plan_integration_setup

__all__ = [
    "ARTIFACT_MANIFEST_NAME",
    "INSTALLATION_RECORD_NAME",
    "INSTALLATION_RECORD_SCHEMA",
    "SERVICE_REGISTRATION_MANIFEST_NAME",
    "SUPPORTED_TOOLS",
    "WINDOWS_11_CORE_PLATFORM_ID",
    "ApprovalStore",
    "BeginnerJourneyResult",
    "ClientConfigurationError",
    "ClientMutation",
    "ClientSetupPlan",
    "DecisionExplanation",
    "DistributionDoctorReport",
    "DoctorFinding",
    "EnvironmentDiscovery",
    "ExperienceMode",
    "InstallResult",
    "InstalledStateRecord",
    "ResourceEnvelope",
    "RiskLevel",
    "ServiceRegistrationAdapter",
    "ServiceRegistrationDriftError",
    "ServiceRegistrationError",
    "ServiceRegistrationManager",
    "ServiceRegistrationManifest",
    "ServiceRegistrationObservation",
    "ServiceRegistrationPlan",
    "ServiceRegistrationResult",
    "ServiceRegistrationRollbackError",
    "ServiceRegistrationSpec",
    "SetupAction",
    "SetupPlan",
    "StateMigrationResult",
    "ToolDiscovery",
    "UnsupportedServicePlatformError",
    "UnsupportedServiceRegistrationAdapter",
    "VerifiedArtifact",
    "WindowsTaskSchedulerRegistrationAdapter",
    "apply_integration_setup",
    "apply_client_enable",
    "apply_client_rollback",
    "canonical_state_root",
    "complete_deferred_uninstall",
    "create_artifact_manifest",
    "detect_resources",
    "discover_canonical_state_root",
    "discover_environment",
    "discover_bridge_command",
    "explain_decision",
    "install",
    "install_plan",
    "installation_record_path",
    "migrate_legacy_state",
    "plan_integration_setup",
    "plan_client_enable",
    "plan_client_rollback",
    "presentation_policy",
    "read_installed_state_record",
    "read_service_registration_manifest",
    "remove_installed_state_record",
    "require_approval",
    "run_distribution_doctor",
    "run_installation_doctor",
    "select_service_registration_adapter",
    "start_beginner_journey",
    "uninstall",
    "uninstall_plan",
    "upgrade",
    "upgrade_plan",
    "verify_artifact",
    "verify_client_integration",
    "write_installed_state_record",
]
