"""Knowledge and controlled evolution package boundary."""

from .evolution import (
    DivergenceReport,
    OverlayPrivilegeError,
    PromotionDeniedError,
    inspect_divergence,
    promote_knowledge,
)
from .model import (
    CandidateOverlay,
    ImprovementProposal,
    KnowledgeItem,
    KnowledgeKind,
    KnowledgeProvenance,
    KnowledgeScope,
    KnowledgeState,
    OverlayUpdateAssessment,
    OverlayValidationStatus,
    PromotionPolicy,
    RevisitKind,
    RevisitTrigger,
    Sensitivity,
    UpdateClassification,
    VerifiedAgainst,
)
from .organizational import (
    KnowledgeApplicability,
    KnowledgeRecommendation,
    OrganizationalKnowledgeError,
    OrganizationalKnowledgeRecord,
    OrganizationalKnowledgeService,
    OrganizationalKnowledgeStore,
)
from .store import InstanceKnowledgeStore, KnowledgeIsolationError, ProjectLessonStore

__all__ = [
    "CandidateOverlay",
    "DivergenceReport",
    "ImprovementProposal",
    "InstanceKnowledgeStore",
    "KnowledgeApplicability",
    "KnowledgeIsolationError",
    "KnowledgeItem",
    "KnowledgeKind",
    "KnowledgeProvenance",
    "KnowledgeRecommendation",
    "KnowledgeScope",
    "KnowledgeState",
    "OrganizationalKnowledgeError",
    "OrganizationalKnowledgeRecord",
    "OrganizationalKnowledgeService",
    "OrganizationalKnowledgeStore",
    "OverlayPrivilegeError",
    "OverlayUpdateAssessment",
    "OverlayValidationStatus",
    "ProjectLessonStore",
    "PromotionDeniedError",
    "PromotionPolicy",
    "RevisitKind",
    "RevisitTrigger",
    "Sensitivity",
    "UpdateClassification",
    "VerifiedAgainst",
    "inspect_divergence",
    "promote_knowledge",
]
